# This is a basic workflow to help you get started with Actions

name: isfhan surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Installing  Node.js 
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12

    - name: Insatlling packages from packges.json
      run: npm install

    - name: creating react app build
      run: npm run build
    # Runs a set of commands using the runners shell
    - name: Installing Surge 
      run: npm install --global surge

    - name: deploying using surge
      run: surge ./build expense-tracker-online.surge.sh --token ${{ secrets.SURGE_TOKEN }}
